### PR TITLE
Fix/event participant

### LINKED ISSUE #28: Event Participant Refactor?
Extract all participant functionality to their own routes so that participants will be added with their own mongoose _id and modifications will be easier since we can use mongoose methods for queries

### PR DESCRIPTION
**Pull request by skyebrownh**
Closes #28

### CODE REVIEW

File: controllers/organizations/organization.js [hunk 1]
```diff
@@ -70,9 +71,6 @@ module.exports = {
       .select('uid')
       .catch(err => next(err));
 
-    if (!publicOrgs)
```
Comment (skyebrownh) [inline controllers/organizations/organization.js:73]: Do empty queries return empty array? Can they be checked with not operator or only by checking length of array?

File: controllers/organizations/user.js [hunk 2]
```diff
@@ -7,11 +7,6 @@ module.exports = {
       organization: res.locals.org.id
     }).catch(err => next(err));
 
-    if (!orgUsers)
```
Comment (skyebrownh) [inline controllers/organizations/user.js:10]: empty query research

File: controllers/organizations/user.js [hunk 3]
```diff
@@ -63,7 +58,7 @@ module.exports = {
         user: { $ne: req.user.id }
       }).catch(err => next(err));
 
-      if (!orgUsers)
```
Comment (skyebrownh) [inline controllers/organizations/user.js:66]: empty query research
